from PyQt5 import QtCore, QtGui, QtWidgets

class Customer_Buying_Page_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1079, 705)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(199, 255, 243);")
        self.stufftable = QtWidgets.QTableWidget(Dialog)
        # self.stufftable.setEnabled(False)
        self.stufftable.setGeometry(QtCore.QRect(400, 90, 651, 501))
        self.stufftable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stufftable.setObjectName("stufftable")
        self.stufftable.setColumnCount(5)
        self.stufftable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stufftable.setItem(2, 4, item)
        self.stuff_codelineedit = QtWidgets.QLineEdit(Dialog)
        self.stuff_codelineedit.setGeometry(QtCore.QRect(150, 60, 221, 21))
        self.stuff_codelineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stuff_codelineedit.setObjectName("stuff_codelineedit")
        self.stuff_codelable = QtWidgets.QLabel(Dialog)
        self.stuff_codelable.setGeometry(QtCore.QRect(10, 60, 131, 20))
        self.stuff_codelable.setObjectName("stuff_codelable")
        self.stufflistchosenlistwidget = QtWidgets.QListWidget(Dialog)
        self.stufflistchosenlistwidget.setGeometry(QtCore.QRect(30, 260, 291, 301))
        self.stufflistchosenlistwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stufflistchosenlistwidget.setObjectName("stufflistchosenlistwidget")
        self.stuff_chosen_lable = QtWidgets.QLabel(Dialog)
        self.stuff_chosen_lable.setGeometry(QtCore.QRect(40, 230, 181, 21))
        self.stuff_chosen_lable.setObjectName("stuff_chosen_lable")
        self.payingmoneybutton = QtWidgets.QPushButton(Dialog)
        self.payingmoneybutton.setGeometry(QtCore.QRect(860, 640, 181, 31))
        self.payingmoneybutton.setObjectName("payingmoneybutton")
        self.backbutton = QtWidgets.QPushButton(Dialog)
        self.backbutton.setGeometry(QtCore.QRect(750, 640, 101, 31))
        self.backbutton.setObjectName("backbutton")
        self.addtolistbutton = QtWidgets.QPushButton(Dialog)
        self.addtolistbutton.setGeometry(QtCore.QRect(110, 110, 171, 31))
        self.addtolistbutton.setObjectName("addtolistbutton")
        self.edit_button = QtWidgets.QPushButton(Dialog)
        self.edit_button.setGeometry(QtCore.QRect(30, 570, 91, 31))
        self.edit_button.setObjectName("edit_button")
        self.delete_button = QtWidgets.QPushButton(Dialog)
        self.delete_button.setGeometry(QtCore.QRect(130, 570, 93, 31))
        self.delete_button.setObjectName("delete_button")
        self.deleteall_button = QtWidgets.QPushButton(Dialog)
        self.deleteall_button.setGeometry(QtCore.QRect(230, 570, 93, 31))
        self.deleteall_button.setObjectName("deleteall_button")
        self.updatestuff_button = QtWidgets.QPushButton(Dialog)
        self.updatestuff_button.setGeometry(QtCore.QRect(420, 50, 131, 31))
        self.updatestuff_button.setObjectName("updatestuff_button")
        self.Details1_lable = QtWidgets.QLabel(Dialog)
        self.Details1_lable.setGeometry(QtCore.QRect(710, 20, 271, 21))
        self.Details1_lable.setObjectName("Details1_lable")
        self.details2_lable = QtWidgets.QLabel(Dialog)
        self.details2_lable.setGeometry(QtCore.QRect(720, 50, 251, 20))
        self.details2_lable.setObjectName("details2_lable")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.stufftable.setSortingEnabled(True)
        item = self.stufftable.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.stufftable.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.stufftable.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.stufftable.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.stufftable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "نام"))
        item = self.stufftable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "برند"))
        item = self.stufftable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "قیمت"))
        item = self.stufftable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "کد"))
        item = self.stufftable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "موجودی"))
        __sortingEnabled = self.stufftable.isSortingEnabled()
        self.stufftable.setSortingEnabled(False)
        self.stufftable.setSortingEnabled(__sortingEnabled)
        self.stuff_codelable.setText(_translate("Dialog", "کد کالا را وارد کنید"))
        self.stuff_chosen_lable.setText(_translate("Dialog", "لیست کالا های مورد علاقه"))
        self.payingmoneybutton.setText(_translate("Dialog", "تسویه کردن لیست خرید"))
        self.backbutton.setText(_translate("Dialog", "قبلی"))
        self.addtolistbutton.setText(_translate("Dialog", "اضافه کردن به لیست"))
        self.edit_button.setText(_translate("Dialog", "تصحیح"))
        self.delete_button.setText(_translate("Dialog", "حذف "))
        self.deleteall_button.setText(_translate("Dialog", "حذف همه"))
        self.updatestuff_button.setText(_translate("Dialog", "به روز رسانی کالا ها"))
        self.Details1_lable.setText(_translate("Dialog", "*در لیست کالا های مورد علاقه بر روی  کالایی که"))
        self.details2_lable.setText(_translate("Dialog", " میخواهید بخرید با توجه به کد آن کلیک کنید*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Customer_Buying_Page_ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

