from PyQt5 import QtCore, QtGui, QtWidgets

class Edit_Housekeeper_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 411)
        self.details_labl = QtWidgets.QLabel(Dialog)
        self.details_labl.setGeometry(QtCore.QRect(120, 30, 261, 20))
        self.details_labl.setObjectName("details_labl")
        self.new_housekeeper_lable = QtWidgets.QLabel(Dialog)
        self.new_housekeeper_lable.setGeometry(QtCore.QRect(260, 200, 91, 20))
        self.new_housekeeper_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.new_housekeeper_lable.setObjectName("new_housekeeper_lable")
        self.back_button = QtWidgets.QPushButton(Dialog)
        self.back_button.setGeometry(QtCore.QRect(80, 330, 93, 28))
        self.back_button.setObjectName("back_button")
        self.new_name_lable = QtWidgets.QLabel(Dialog)
        self.new_name_lable.setGeometry(QtCore.QRect(280, 160, 55, 16))
        self.new_name_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.new_name_lable.setObjectName("new_name_lable")
        self.new_password_lable = QtWidgets.QLabel(Dialog)
        self.new_password_lable.setGeometry(QtCore.QRect(280, 240, 55, 16))
        self.new_password_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.new_password_lable.setObjectName("new_password_lable")
        self.new_email_lable = QtWidgets.QLabel(Dialog)
        self.new_email_lable.setGeometry(QtCore.QRect(280, 280, 55, 16))
        self.new_email_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.new_email_lable.setObjectName("new_email_lable")
        self.newhousekeeperlineedit = QtWidgets.QLineEdit(Dialog)
        self.newhousekeeperlineedit.setGeometry(QtCore.QRect(90, 200, 151, 21))
        self.newhousekeeperlineedit.setObjectName("newhousekeeperlineedit")
        self.new_name_lineedit = QtWidgets.QLineEdit(Dialog)
        self.new_name_lineedit.setGeometry(QtCore.QRect(90, 160, 151, 20))
        self.new_name_lineedit.setObjectName("new_name_lineedit")
        self.new_password_lineedit = QtWidgets.QLineEdit(Dialog)
        self.new_password_lineedit.setGeometry(QtCore.QRect(90, 240, 151, 21))
        self.new_password_lineedit.setObjectName("new_password_lineedit")
        self.new_email_lineedit = QtWidgets.QLineEdit(Dialog)
        self.new_email_lineedit.setGeometry(QtCore.QRect(90, 280, 151, 21))
        self.new_email_lineedit.setObjectName("new_email_lineedit")
        self.enter_housekeeper_wants_to_edit_lineedit = QtWidgets.QLineEdit(Dialog)
        self.enter_housekeeper_wants_to_edit_lineedit.setGeometry(QtCore.QRect(20, 60, 201, 21))
        self.enter_housekeeper_wants_to_edit_lineedit.setObjectName("enter_housekeeper_wants_to_edit_lineedit")
        self.edit_button = QtWidgets.QPushButton(Dialog)
        self.edit_button.setGeometry(QtCore.QRect(180, 330, 93, 28))
        self.edit_button.setObjectName("edit_button")
        self.detailslable = QtWidgets.QLabel(Dialog)
        self.detailslable.setGeometry(QtCore.QRect(100, 120, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.detailslable.setFont(font)
        self.detailslable.setStyleSheet("color: rgb(255, 42, 0);")
        self.detailslable.setObjectName("detailslable")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.details_labl.setText(_translate("Dialog", "نام کاربری، کاربری که میخواهید تصحیح کنید ؟"))
        self.new_housekeeper_lable.setText(_translate("Dialog", "نام کاربری جدید"))
        self.back_button.setText(_translate("Dialog", "برگشت"))
        self.new_name_lable.setText(_translate("Dialog", "نام جدید"))
        self.new_password_lable.setText(_translate("Dialog", "رمز عبور"))
        self.new_email_lable.setText(_translate("Dialog", "ایمیل"))
        self.edit_button.setText(_translate("Dialog", "تصحیح"))
        self.detailslable.setText(_translate("Dialog", "هشدار : تمام فیلد های زیر جایگزین خواهند شد"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Edit_Housekeeper_ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

