from PyQt5 import QtCore, QtGui, QtWidgets

class Factor_Table_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(896, 479)
        Dialog.setStyleSheet("background-color: rgb(226, 254, 255);")
        self.factor_table = QtWidgets.QTableWidget(Dialog)
        # self.factor_table.setEnabled(False)
        self.factor_table.setGeometry(QtCore.QRect(10, 30, 521, 421))
        self.factor_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.factor_table.setObjectName("factor_table")
        self.factor_table.setColumnCount(4)
        self.factor_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.factor_table.setHorizontalHeaderItem(3, item)
        self.pay_button = QtWidgets.QPushButton(Dialog)
        self.pay_button.setGeometry(QtCore.QRect(710, 410, 131, 31))
        self.pay_button.setStyleSheet("background-color: rgb(234, 255, 244);")
        self.pay_button.setObjectName("pay_button")
        self.back_button = QtWidgets.QPushButton(Dialog)
        self.back_button.setGeometry(QtCore.QRect(590, 410, 101, 31))
        self.back_button.setObjectName("back_button")
        self.delete_from_list_button = QtWidgets.QPushButton(Dialog)
        self.delete_from_list_button.setGeometry(QtCore.QRect(750, 210, 93, 31))
        self.delete_from_list_button.setObjectName("delete_from_list_button")
        self.count_off_code_button = QtWidgets.QPushButton(Dialog)
        self.count_off_code_button.setGeometry(QtCore.QRect(750, 80, 131, 31))
        self.count_off_code_button.setObjectName("count_off_code_button")
        self.off_code_lineedit = QtWidgets.QLineEdit(Dialog)
        self.off_code_lineedit.setGeometry(QtCore.QRect(550, 90, 181, 21))
        self.off_code_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.off_code_lineedit.setObjectName("off_code_lineedit")
        self.details_lable = QtWidgets.QLabel(Dialog)
        self.details_lable.setGeometry(QtCore.QRect(550, 190, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.details_lable.setFont(font)
        self.details_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.details_lable.setObjectName("details_lable")
        self.delete_item_lineedit = QtWidgets.QLineEdit(Dialog)
        self.delete_item_lineedit.setGeometry(QtCore.QRect(550, 220, 181, 21))
        self.delete_item_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete_item_lineedit.setObjectName("delete_item_lineedit")
        self.if_lable = QtWidgets.QLabel(Dialog)
        self.if_lable.setGeometry(QtCore.QRect(790, 56, 55, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.if_lable.setFont(font)
        self.if_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.if_lable.setObjectName("if_lable")
        self.update_factor_button = QtWidgets.QPushButton(Dialog)
        self.update_factor_button.setGeometry(QtCore.QRect(550, 27, 181, 31))
        self.update_factor_button.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.factor_table.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.factor_table.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.factor_table.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.factor_table.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.factor_table.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.factor_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.factor_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Brand"))
        item = self.factor_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Money"))
        item = self.factor_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Code"))
        self.pay_button.setText(_translate("Dialog", "پرداخت"))
        self.back_button.setText(_translate("Dialog", "برگشت"))
        self.delete_from_list_button.setText(_translate("Dialog", "حذف از لیست"))
        self.count_off_code_button.setText(_translate("Dialog", "محاسبه ی کد تخفیف"))
        self.details_lable.setText(_translate("Dialog", "*کد ایتمی که نمیخواید را وارد کنید*"))
        self.if_lable.setText(_translate("Dialog", "اگر دارید"))
        self.update_factor_button.setText(_translate("Dialog", "به روز کردن لیست فاکتور"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Factor_Table_ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

