from PyQt5 import QtCore, QtGui, QtWidgets

class Manager_Housekeeper_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(794, 499)
        Dialog.setStyleSheet("background-color: rgb(225, 255, 238);")
        self.show_registred_warehousekeeper_table = QtWidgets.QTableWidget(Dialog)
        self.show_registred_warehousekeeper_table.setGeometry(QtCore.QRect(270, 20, 511, 421))
        self.show_registred_warehousekeeper_table.setObjectName("show_registred_warehousekeeper_table")
        self.show_registred_warehousekeeper_table.setColumnCount(4)
        self.show_registred_warehousekeeper_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.show_registred_warehousekeeper_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_registred_warehousekeeper_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_registred_warehousekeeper_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_registred_warehousekeeper_table.setHorizontalHeaderItem(3, item)
        self.Delete_user_button = QtWidgets.QPushButton(Dialog)
        self.Delete_user_button.setGeometry(QtCore.QRect(30, 270, 93, 28))
        self.Delete_user_button.setObjectName("Delete_user_button")
        self.edit_housekeeper_info_button = QtWidgets.QPushButton(Dialog)
        self.edit_housekeeper_info_button.setGeometry(QtCore.QRect(20, 50, 121, 31))
        self.edit_housekeeper_info_button.setObjectName("edit_housekeeper_info_button")
        self.back_button = QtWidgets.QPushButton(Dialog)
        self.back_button.setGeometry(QtCore.QRect(20, 390, 93, 28))
        self.back_button.setObjectName("back_button")
        self.update_table_button = QtWidgets.QPushButton(Dialog)
        self.update_table_button.setGeometry(QtCore.QRect(150, 50, 101, 31))
        self.update_table_button.setObjectName("update_table_button")
        self.entername_details_label = QtWidgets.QLabel(Dialog)
        self.entername_details_label.setGeometry(QtCore.QRect(50, 210, 201, 21))
        self.entername_details_label.setAlignment(QtCore.Qt.AlignCenter)
        self.entername_details_label.setObjectName("entername_details_label")
        self.enter_username_to_delete_lineedit = QtWidgets.QLineEdit(Dialog)
        self.enter_username_to_delete_lineedit.setGeometry(QtCore.QRect(20, 240, 201, 21))
        self.enter_username_to_delete_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_username_to_delete_lineedit.setObjectName("enter_username_to_delete_lineedit")
        self.add_new_housekeeper_button = QtWidgets.QPushButton(Dialog)
        self.add_new_housekeeper_button.setGeometry(QtCore.QRect(20, 90, 121, 31))
        self.add_new_housekeeper_button.setObjectName("add_new_housekeeper_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.show_registred_warehousekeeper_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "نام"))
        item = self.show_registred_warehousekeeper_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "نام کاربری"))
        item = self.show_registred_warehousekeeper_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "رمز عبور"))
        item = self.show_registred_warehousekeeper_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "ایمیل"))
        self.Delete_user_button.setText(_translate("Dialog", "حذف"))
        self.edit_housekeeper_info_button.setText(_translate("Dialog", "تصحیح اطلاعات کاربر"))
        self.back_button.setText(_translate("Dialog", "برگشت"))
        self.update_table_button.setText(_translate("Dialog", "بروز رسانی داده"))
        self.entername_details_label.setText(_translate("Dialog", "نام کاربری را برای حذف کاربر وارد کنید"))
        self.add_new_housekeeper_button.setText(_translate("Dialog", "اضافه کردن کاربر"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Manager_Housekeeper_ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

