from PyQt5 import QtCore, QtGui, QtWidgets

class SignupPage_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 500)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(225, 255, 234);")
        self.namelbl = QtWidgets.QLabel(Dialog)
        self.namelbl.setGeometry(QtCore.QRect(430, 120, 55, 16))
        self.namelbl.setObjectName("namelbl")
        self.emaillable = QtWidgets.QLabel(Dialog)
        self.emaillable.setGeometry(QtCore.QRect(420, 220, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.emaillable.setFont(font)
        self.emaillable.setAlignment(QtCore.Qt.AlignCenter)
        self.emaillable.setObjectName("emaillable")
        self.usernamelbl = QtWidgets.QLabel(Dialog)
        self.usernamelbl.setGeometry(QtCore.QRect(430, 170, 91, 21))
        self.usernamelbl.setAlignment(QtCore.Qt.AlignCenter)
        self.usernamelbl.setObjectName("usernamelbl")
        self.passwordreplable = QtWidgets.QLabel(Dialog)
        self.passwordreplable.setGeometry(QtCore.QRect(430, 310, 101, 20))
        self.passwordreplable.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordreplable.setObjectName("passwordreplable")
        self.passwordlbl = QtWidgets.QLabel(Dialog)
        self.passwordlbl.setGeometry(QtCore.QRect(440, 270, 81, 21))
        self.passwordlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordlbl.setObjectName("passwordlbl")
        self.namelinedit = QtWidgets.QLineEdit(Dialog)
        self.namelinedit.setGeometry(QtCore.QRect(220, 120, 181, 22))
        self.namelinedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.namelinedit.setObjectName("namelinedit")
        self.usernamelineedit = QtWidgets.QLineEdit(Dialog)
        self.usernamelineedit.setGeometry(QtCore.QRect(220, 170, 181, 22))
        self.usernamelineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.usernamelineedit.setObjectName("usernamelineedit")
        self.emaillineedit = QtWidgets.QLineEdit(Dialog)
        self.emaillineedit.setGeometry(QtCore.QRect(220, 220, 181, 21))
        self.emaillineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.emaillineedit.setObjectName("emaillineedit")
        self.passwordlineedit = QtWidgets.QLineEdit(Dialog)
        self.passwordlineedit.setGeometry(QtCore.QRect(220, 270, 181, 20))
        self.passwordlineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passwordlineedit.setObjectName("passwordlineedit")
        self.passwordreplineedit = QtWidgets.QLineEdit(Dialog)
        self.passwordreplineedit.setGeometry(QtCore.QRect(220, 310, 181, 21))
        self.passwordreplineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passwordreplineedit.setObjectName("passwordreplineedit")
        self.signupbutton = QtWidgets.QPushButton(Dialog)
        self.signupbutton.setGeometry(QtCore.QRect(310, 390, 93, 28))
        self.signupbutton.setObjectName("signupbutton")
        self.backbutton = QtWidgets.QPushButton(Dialog)
        self.backbutton.setGeometry(QtCore.QRect(210, 390, 93, 28))
        self.backbutton.setObjectName("backbutton")
        self.this_user_name_exists_lable = QtWidgets.QLabel(Dialog)
        self.this_user_name_exists_lable.setGeometry(QtCore.QRect(210, 80, 181, 31))
        self.this_user_name_exists_lable.setStyleSheet("color: rgb(255, 0, 4);")
        self.this_user_name_exists_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.this_user_name_exists_lable.setObjectName("this_user_name_exists_lable")
        self.passwords_are_not_same_lable = QtWidgets.QLabel(Dialog)
        self.passwords_are_not_same_lable.setGeometry(QtCore.QRect(234, 340, 161, 20))
        self.passwords_are_not_same_lable.setStyleSheet("color: rgb(255, 0, 0);")
        self.passwords_are_not_same_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.passwords_are_not_same_lable.setObjectName("passwords_are_not_same_lable")
        self.onyourown = QtWidgets.QLabel(Dialog)
        self.onyourown.setGeometry(QtCore.QRect(160, 220, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.onyourown.setFont(font)
        self.onyourown.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.onyourown.setObjectName("onyourown")
        self.namealarm = QtWidgets.QLabel(Dialog)
        self.namealarm.setGeometry(QtCore.QRect(54, 120, 161, 21))
        self.namealarm.setStyleSheet("color: rgb(255, 0, 4);")
        self.namealarm.setObjectName("namealarm")
        self.usernamealarm = QtWidgets.QLabel(Dialog)
        self.usernamealarm.setGeometry(QtCore.QRect(50, 170, 161, 21))
        self.usernamealarm.setStyleSheet("color: rgb(255, 0, 4);")
        self.usernamealarm.setObjectName("usernamealarm")
        self.passalarm = QtWidgets.QLabel(Dialog)
        self.passalarm.setGeometry(QtCore.QRect(50, 270, 161, 20))
        self.passalarm.setStyleSheet("color: rgb(255, 0, 4);")
        self.passalarm.setObjectName("passalarm")
        self.passrepalarm = QtWidgets.QLabel(Dialog)
        self.passrepalarm.setGeometry(QtCore.QRect(50, 310, 161, 20))
        self.passrepalarm.setStyleSheet("color: rgb(255, 0, 4);")
        self.passrepalarm.setObjectName("passrepalarm")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.namelbl.setText(_translate("Dialog", "نام"))
        self.emaillable.setText(_translate("Dialog", "ایمیل"))
        self.usernamelbl.setText(_translate("Dialog", "نام کاربری"))
        self.passwordreplable.setText(_translate("Dialog", "تکرار رمز عبور"))
        self.passwordlbl.setText(_translate("Dialog", "رمز عبور"))
        self.signupbutton.setText(_translate("Dialog", "ثبت نام "))
        self.backbutton.setText(_translate("Dialog", "قبلی"))
        # self.this_user_name_exists_lable.setText(_translate("Dialog", "این نام کاربری موجود میباشد "))
        # self.passwords_are_not_same_lable.setText(_translate("Dialog", "رمز عبور هماهنگ نیست"))
        self.onyourown.setText(_translate("Dialog", "*اختیاری"))
        # self.namealarm.setText(_translate("Dialog", "این جایگاه نباید خالی باشد"))
        # self.usernamealarm.setText(_translate("Dialog", "این جایگاه نباید خالی باشد"))
        # self.passalarm.setText(_translate("Dialog", "این جایگاه نباید خالی باشد"))
        # self.passrepalarm.setText(_translate("Dialog", "این جایگاه نباید خالی باشد"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = SignupPage_ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

