from PyQt5 import QtCore, QtGui, QtWidgets

class Update_Items_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(454, 501)
        Dialog.setStyleSheet("background-color: rgb(198, 255, 252);")
        self.codeitem_update_lable = QtWidgets.QLabel(Dialog)
        self.codeitem_update_lable.setGeometry(QtCore.QRect(270, 30, 151, 21))
        self.codeitem_update_lable.setObjectName("codeitem_update_lable")
        self.code_lineedit = QtWidgets.QLineEdit(Dialog)
        self.code_lineedit.setGeometry(QtCore.QRect(40, 60, 191, 21))
        self.code_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.code_lineedit.setObjectName("code_lineedit")
        self.name_update_lable = QtWidgets.QLabel(Dialog)
        self.name_update_lable.setGeometry(QtCore.QRect(320, 170, 41, 20))
        self.name_update_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.name_update_lable.setObjectName("name_update_lable")
        self.brand_update_lable = QtWidgets.QLabel(Dialog)
        self.brand_update_lable.setGeometry(QtCore.QRect(320, 210, 41, 20))
        self.brand_update_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.brand_update_lable.setObjectName("brand_update_lable")
        self.money_update_lable = QtWidgets.QLabel(Dialog)
        self.money_update_lable.setGeometry(QtCore.QRect(320, 250, 41, 21))
        self.money_update_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.money_update_lable.setObjectName("money_update_lable")
        self.remaining_update_lable = QtWidgets.QLabel(Dialog)
        self.remaining_update_lable.setGeometry(QtCore.QRect(320, 290, 51, 21))
        self.remaining_update_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.remaining_update_lable.setObjectName("remaining_update_lable")
        self.detailslable = QtWidgets.QLabel(Dialog)
        self.detailslable.setGeometry(QtCore.QRect(170, 130, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.detailslable.setFont(font)
        self.detailslable.setStyleSheet("color: rgb(255, 14, 18);")
        self.detailslable.setAlignment(QtCore.Qt.AlignCenter)
        self.detailslable.setObjectName("detailslable")
        self.name_lineedit = QtWidgets.QLineEdit(Dialog)
        self.name_lineedit.setGeometry(QtCore.QRect(70, 170, 221, 21))
        self.name_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_lineedit.setObjectName("name_lineedit")
        self.brand_lineedit = QtWidgets.QLineEdit(Dialog)
        self.brand_lineedit.setGeometry(QtCore.QRect(70, 210, 221, 21))
        self.brand_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.brand_lineedit.setObjectName("brand_lineedit")
        self.money_lineedit = QtWidgets.QLineEdit(Dialog)
        self.money_lineedit.setGeometry(QtCore.QRect(70, 250, 221, 22))
        self.money_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.money_lineedit.setObjectName("money_lineedit")
        self.remain_lineedit = QtWidgets.QLineEdit(Dialog)
        self.remain_lineedit.setGeometry(QtCore.QRect(70, 290, 221, 22))
        self.remain_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.remain_lineedit.setObjectName("remain_lineedit")
        self.update_button = QtWidgets.QPushButton(Dialog)
        self.update_button.setGeometry(QtCore.QRect(290, 370, 81, 31))
        self.update_button.setObjectName("update_button")
        self.cancelbutton = QtWidgets.QPushButton(Dialog)
        self.cancelbutton.setGeometry(QtCore.QRect(190, 370, 91, 31))
        self.cancelbutton.setObjectName("cancelbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.codeitem_update_lable.setText(_translate("Dialog", "کد آیتم مورد نظر را وارد کنید"))
        self.name_update_lable.setText(_translate("Dialog", "نام "))
        self.brand_update_lable.setText(_translate("Dialog", "برند"))
        self.money_update_lable.setText(_translate("Dialog", "قیمت"))
        self.remaining_update_lable.setText(_translate("Dialog", "موجودی"))
        self.detailslable.setText(_translate("Dialog", "*فیلد های زیر جایگزین خواهند شد*"))
        self.update_button.setText(_translate("Dialog", "بروز شود"))
        self.cancelbutton.setText(_translate("Dialog", "برگشت"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Update_Items_ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

